
from codegen.ue4_stub import *

from Script.FactoryGame import FGDestructibleActor
from Script.Engine import K2_GetActorLocation
from Game.FactoryGame.Equipment.NobeliskDetonator.Audio.WorldDestruction.Play_Nobelisk_WorldDestruction_Boulder import Play_Nobelisk_WorldDestruction_Boulder
from Script.CoreUObject import Vector
from Script.AkAudio import PostAkEventAtLocation
from Game.FactoryGame.Equipment.C4Dispenser.BP_DestructibleLargeRock import ExecuteUbergraph_BP_DestructibleLargeRock
from Script.AkAudio import AkComponent
from Script.AkAudio import Default__AkGameplayStatics

class BP_DestructibleLargeRock(FGDestructibleActor):
    mStaticMeshProxy = Namespace(BodyInstance={'ObjectType': 0, 'CollisionEnabled': 0, 'SleepFamily': 'ESleepFamily::Normal', 'DOFMode': 0, 'bUseCCD': False, 'bNotifyRigidBodyCollision': False, 'bSimulatePhysics': False, 'bOverrideMass': False, 'bEnableGravity': True, 'bAutoWeld': True, 'bStartAwake': True, 'bGenerateWakeEvents': False, 'bUpdateMassWhenScaleChanges': False, 'bLockTranslation': True, 'bLockRotation': True, 'bLockXTranslation': False, 'bLockYTranslation': False, 'bLockZTranslation': False, 'bLockXRotation': False, 'bLockYRotation': False, 'bLockZRotation': False, 'bOverrideMaxAngularVelocity': False, 'bOverrideMaxDepenetrationVelocity': False, 'bOverrideWalkableSlopeOnInstance': False, 'bInterpolateWhenSubStepping': True, 'CollisionProfileName': 'NoCollision', 'CollisionResponses': {'ResponseArray': [{'Channel': 'WorldStatic', 'Response': 0}, {'Channel': 'WorldDynamic', 'Response': 0}, {'Channel': 'Pawn', 'Response': 0}, {'Channel': 'Visibility', 'Response': 0}, {'Channel': 'Camera', 'Response': 0}, {'Channel': 'PhysicsBody', 'Response': 0}, {'Channel': 'Vehicle', 'Response': 0}, {'Channel': 'Destructible', 'Response': 0}, {'Channel': 'Projectile', 'Response': 0}, {'Channel': 'Resource', 'Response': 0}]}, 'MaxDepenetrationVelocity': 0, 'MassInKgOverride': 100, 'LinearDamping': 0.009999999776482582, 'AngularDamping': 0, 'CustomDOFPlaneNormal': {'X': 0, 'Y': 0, 'Z': 0}, 'COMNudge': {'X': 0, 'Y': 0, 'Z': 0}, 'MassScale': 1, 'InertiaTensorScale': {'X': 1, 'Y': 1, 'Z': 1}, 'WalkableSlopeOverride': {'WalkableSlopeBehavior': 0, 'WalkableSlopeAngle': 0}, 'PhysMaterialOverride': {'$Empty': True}, 'MaxAngularVelocity': 3600, 'CustomSleepThresholdMultiplier': 1, 'StabilizationThresholdMultiplier': 1, 'PhysicsBlendWeight': 0, 'PositionSolverIterationCount': 8, 'VelocitySolverIterationCount': 1}, CachedMaxDrawDistance=25000, LDMaxDrawDistance=25000, Mobility=0, ObjectClass='/Script/Engine.StaticMeshComponent', ObjectFlags=2883617, ObjectName='StaticMeshProxy', StaticMesh={'$AssetPath': '/Game/FactoryGame/World/Environment/Rock/DestructibleRock/Mesh/DestructibleRock_Big.DestructibleRock_Big'})
    DestructibleComponent = Namespace(AttachParent={'$ObjectClass': '/Script/Engine.StaticMeshComponent', '$ObjectFlags': 2883617, '$ObjectName': 'StaticMeshProxy', 'StaticMesh': {'$AssetPath': '/Game/FactoryGame/World/Environment/Rock/DestructibleRock/Mesh/DestructibleRock_Big.DestructibleRock_Big'}, 'LDMaxDrawDistance': 25000, 'CachedMaxDrawDistance': 25000, 'BodyInstance': {'ObjectType': 0, 'CollisionEnabled': 0, 'SleepFamily': 'ESleepFamily::Normal', 'DOFMode': 0, 'bUseCCD': False, 'bNotifyRigidBodyCollision': False, 'bSimulatePhysics': False, 'bOverrideMass': False, 'bEnableGravity': True, 'bAutoWeld': True, 'bStartAwake': True, 'bGenerateWakeEvents': False, 'bUpdateMassWhenScaleChanges': False, 'bLockTranslation': True, 'bLockRotation': True, 'bLockXTranslation': False, 'bLockYTranslation': False, 'bLockZTranslation': False, 'bLockXRotation': False, 'bLockYRotation': False, 'bLockZRotation': False, 'bOverrideMaxAngularVelocity': False, 'bOverrideMaxDepenetrationVelocity': False, 'bOverrideWalkableSlopeOnInstance': False, 'bInterpolateWhenSubStepping': True, 'CollisionProfileName': 'NoCollision', 'CollisionResponses': {'ResponseArray': [{'Channel': 'WorldStatic', 'Response': 0}, {'Channel': 'WorldDynamic', 'Response': 0}, {'Channel': 'Pawn', 'Response': 0}, {'Channel': 'Visibility', 'Response': 0}, {'Channel': 'Camera', 'Response': 0}, {'Channel': 'PhysicsBody', 'Response': 0}, {'Channel': 'Vehicle', 'Response': 0}, {'Channel': 'Destructible', 'Response': 0}, {'Channel': 'Projectile', 'Response': 0}, {'Channel': 'Resource', 'Response': 0}]}, 'MaxDepenetrationVelocity': 0, 'MassInKgOverride': 100, 'LinearDamping': 0.009999999776482582, 'AngularDamping': 0, 'CustomDOFPlaneNormal': {'X': 0, 'Y': 0, 'Z': 0}, 'COMNudge': {'X': 0, 'Y': 0, 'Z': 0}, 'MassScale': 1, 'InertiaTensorScale': {'X': 1, 'Y': 1, 'Z': 1}, 'WalkableSlopeOverride': {'WalkableSlopeBehavior': 0, 'WalkableSlopeAngle': 0}, 'PhysMaterialOverride': {'$Empty': True}, 'MaxAngularVelocity': 3600, 'CustomSleepThresholdMultiplier': 1, 'StabilizationThresholdMultiplier': 1, 'PhysicsBlendWeight': 0, 'PositionSolverIterationCount': 8, 'VelocitySolverIterationCount': 1}, 'Mobility': 0}, FractureEffects=[{'ParticleSystem': {'$Empty': True}, 'Sound': {'$Empty': True}}, {'ParticleSystem': {'$Empty': True}, 'Sound': {'$Empty': True}}], ObjectClass='/Script/ApexDestruction.DestructibleComponent', ObjectFlags=2883617, ObjectName='DestructibleComponent0', OverrideMaterials=[{'$Empty': True}, {'$AssetPath': '/Game/FactoryGame/World/Environment/Rock/DestructibleRock/Material/DestructibleRocks_Inst.DestructibleRocks_Inst'}, {'$AssetPath': '/Game/FactoryGame/World/Environment/Rock/DestructibleRock/Material/DestructibleRocks_Inst.DestructibleRocks_Inst'}], SkeletalMesh={'$AssetPath': '/Game/FactoryGame/World/Environment/Rock/DestructibleRock/Mesh/DestructibleRock_Big_DM.DestructibleRock_Big_DM'}, bHiddenInGame=True, bVisible=False)
    OnActorFracture = 0
    bReplicates = True
    RemoteRole = 1
    RootComponent = Namespace(BodyInstance={'ObjectType': 0, 'CollisionEnabled': 0, 'SleepFamily': 'ESleepFamily::Normal', 'DOFMode': 0, 'bUseCCD': False, 'bNotifyRigidBodyCollision': False, 'bSimulatePhysics': False, 'bOverrideMass': False, 'bEnableGravity': True, 'bAutoWeld': True, 'bStartAwake': True, 'bGenerateWakeEvents': False, 'bUpdateMassWhenScaleChanges': False, 'bLockTranslation': True, 'bLockRotation': True, 'bLockXTranslation': False, 'bLockYTranslation': False, 'bLockZTranslation': False, 'bLockXRotation': False, 'bLockYRotation': False, 'bLockZRotation': False, 'bOverrideMaxAngularVelocity': False, 'bOverrideMaxDepenetrationVelocity': False, 'bOverrideWalkableSlopeOnInstance': False, 'bInterpolateWhenSubStepping': True, 'CollisionProfileName': 'NoCollision', 'CollisionResponses': {'ResponseArray': [{'Channel': 'WorldStatic', 'Response': 0}, {'Channel': 'WorldDynamic', 'Response': 0}, {'Channel': 'Pawn', 'Response': 0}, {'Channel': 'Visibility', 'Response': 0}, {'Channel': 'Camera', 'Response': 0}, {'Channel': 'PhysicsBody', 'Response': 0}, {'Channel': 'Vehicle', 'Response': 0}, {'Channel': 'Destructible', 'Response': 0}, {'Channel': 'Projectile', 'Response': 0}, {'Channel': 'Resource', 'Response': 0}]}, 'MaxDepenetrationVelocity': 0, 'MassInKgOverride': 100, 'LinearDamping': 0.009999999776482582, 'AngularDamping': 0, 'CustomDOFPlaneNormal': {'X': 0, 'Y': 0, 'Z': 0}, 'COMNudge': {'X': 0, 'Y': 0, 'Z': 0}, 'MassScale': 1, 'InertiaTensorScale': {'X': 1, 'Y': 1, 'Z': 1}, 'WalkableSlopeOverride': {'WalkableSlopeBehavior': 0, 'WalkableSlopeAngle': 0}, 'PhysMaterialOverride': {'$Empty': True}, 'MaxAngularVelocity': 3600, 'CustomSleepThresholdMultiplier': 1, 'StabilizationThresholdMultiplier': 1, 'PhysicsBlendWeight': 0, 'PositionSolverIterationCount': 8, 'VelocitySolverIterationCount': 1}, CachedMaxDrawDistance=25000, LDMaxDrawDistance=25000, Mobility=0, ObjectClass='/Script/Engine.StaticMeshComponent', ObjectFlags=2883617, ObjectName='StaticMeshProxy', StaticMesh={'$AssetPath': '/Game/FactoryGame/World/Environment/Rock/DestructibleRock/Mesh/DestructibleRock_Big.DestructibleRock_Big'})
    
    def PlayDestructEffects(self):
        self.ExecuteUbergraph_BP_DestructibleLargeRock(10)
    

    def ExecuteUbergraph_BP_DestructibleLargeRock(self):
        ReturnValue: Vector = self.K2_GetActorLocation()
        ReturnValue_0: Ptr[AkComponent] = Default__AkGameplayStatics.PostAkEventAtLocation(self, Play_Nobelisk_WorldDestruction_Boulder, ReturnValue, Rotator::FromPitchYawRoll(0, 0, 0))
    
